### ISSUE TITLE
[URL]: Request new URL

### ISSUE THREAD

**Issue by harsshhan** [Rahuletto/AcademiaPro#22]
- [X] Is this relatable to SRM students
- [X] is this safe and valid

URL: https://itkmservicedesk.srmist.edu.in/

**Comment by Rahuletto** [comment]
is there any more SRM links to be added? 
Please include them in this issue too

Thanks

**Comment by Rahuletto** [comment]
Added the URL in commit 1702d10fba929b6fa051b7a369cae878e39027ad
