### ISSUE TITLE
[ISSUE] Timetable Link 

### ISSUE THREAD

**Issue by risv1** [Rahuletto/AcademiaPro#25]
**Describe the bug**
The timetable sidebar link does not work.

**Expected behavior**
Scroll back up to the timetable section on click.

**Fix**
Add the id of timetable to the respective section on the /academia page :)

**Comment by risv1** [comment]
Pretty sure the id has been added, but doesn't work, check it out 👍

**Comment by Rahuletto** [comment]
Fixing in 6c39753

Thanks for calling it out
