### ISSUE TITLE
[ISSUE] Bug report

### ISSUE THREAD

**Issue by SG7-SourishGhosh** [Rahuletto/AcademiaPro#57]
**Can't login after password change**
I have changed my student portal password due to some reason and now I can't login through Academia pro neither via old password nor the new

**To Reproduce**
1. Go to 'https://ssp.srmist.edu.in/resetpassword/'
2. Put down your credentials and set the new password
3. Go back to academia pro

**Expected behavior**
To login as usual and make use of the app

**Desktop**
 - OS: Windows 11 (23h2)
 - Browser: Opera GX
 - Version 22
 
**Smartphone**
 - Device: Vivo S1 pro
 - OS: Android 14
 - Used the mobile application

**Comment by Rahuletto** [comment]
Student portal and SRM Academia uses two different passwords, as you mentioned you changed your password in student portal, which is only reflected on student portal. not on academia or academiapro, can u try logging in again with the old academia password? it can also be server might be down when u were trying

**Comment by SG7-SourishGhosh** [comment]
ThankQ the old password did work out
