### ISSUE TITLE
[URL] Mess menu

### ISSUE THREAD

**Issue by dinonomous** [Rahuletto/AcademiaPro#7]
messmenue it shows what is there in the mess update according to new table provided by sanyasi mess combined with a todolist so that you will not forget anything on your way to mess

this is just a static website it is safe and will not collect any data

- [x] Is this relatable to SRM students
- [x] is this safe and valid

URL: https://messmenue.netlify.app/

**Comment by Rahuletto** [comment]
How is this different from https://whatsinmess.vercel.app/ ?

**Comment by Rahuletto** [comment]
This URL is on hold until i get a response

**Comment by root-daemon** [comment]
@dinonomous

**Comment by Rahuletto** [comment]
Closing the issue for stale/no reply.

Open this issue when you wanted to add
